server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost/ecwsdb?createDatabaseIfNotExists=true
    username: root
    password: "0000"
    driver-class-name: com.mysql.cj.jdbc.Driver
    platform: mysql
  mvc:
    cors:
      allowed-origins:
        - http://localhost:4200
  jpa:
    hibernate:
      ddl-auto: create

